version: '3.4'

services:
  blazorsignalrbackplanetest:
    image: blazorsignalrbackplanetest:dev
    container_name: BlazorSignalRBackplaneTest
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "BlazorSignalRBackplaneTest"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=
    volumes:
      - C:\Users\Jasper\source\repos\BlazorSignalRBackplaneTest\BlazorSignalRBackplaneTest:/app
      - C:\Users\Jasper\source\repos\BlazorSignalRBackplaneTest:/src
      - C:\Users\Jasper\vsdbg\vs2017u5:/remote_debugger:rw
      - C:\Users\Jasper\.nuget\packages\:/root/.nuget/packages:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /root/.nuget/packages  \"/app/bin/Debug/net7.0/BlazorSignalRBackplaneTest.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
  blazorsignalrbackplanetest2:
    image: blazorsignalrbackplanetest:dev
    container_name: BlazorSignalRBackplaneTest_1
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "BlazorSignalRBackplaneTest"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=
    volumes:
      - C:\Users\Jasper\source\repos\BlazorSignalRBackplaneTest\BlazorSignalRBackplaneTest:/app
      - C:\Users\Jasper\source\repos\BlazorSignalRBackplaneTest:/src
      - C:\Users\Jasper\vsdbg\vs2017u5:/remote_debugger:rw
      - C:\Users\Jasper\.nuget\packages\:/root/.nuget/packages:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /root/.nuget/packages  \"/app/bin/Debug/net7.0/BlazorSignalRBackplaneTest.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
